// src/components/blog/ViewCounter.tsx
import { useViewCount } from "@/components/blog/utils";
import { Skeleton } from "@/components/common/SkeletonLoader.vue";

const isSSR = import.meta.env.SSR;

type ViewCounterProps = {
	id: string;
};

export const ViewCounter = ({ id }: ViewCounterProps) => {
	const { isLoading, error, viewCount } = useViewCount(id);

	if (error) {
		return;
	}

	return isSSR || isLoading || viewCount === null ? (
		<Skeleton className="w-[8ch]" />
	) : (
		<p className="inline-block">{viewCount.toLocaleString()} views</p>
	);
};

// src/components/blog/ViewCounter.vue
<script setup lang="ts">
import SkeletonLoader from "@/components/common/SkeletonLoader.vue";
import { useViewCount } from "@/components/blog/useViewCount.ts";

const isSSR = import.meta.env.SSR;

const props = defineProps<{
	id: string;
}>();

const { isLoading, error, viewCount } = useViewCount(props.id);
</script>

<template>
	<template v-if="!error">
		<SkeletonLoader v-if="isSSR || isLoading || viewCount === null" />

		<p v-else>{{ `${viewCount.toLocaleString()} views` }}</p>
	</template>
</template>
