// src/components/common/ViewCounter.tsx
import { actions } from "astro:actions";
import { useState } from "react";
import { useOnMount } from "@/utils/useOnMount.ts";

export const ViewCounter = ({
	id,
	shouldIncrease = false,
}: { id: string; shouldIncrease?: boolean }) => {
	const [isLoading, setIsLoading] = useState(true);
	const [viewCount, setViewCount] = useState<number | null>(null);

	useOnMount(() => {
		const fetchData = async () => {
			const { data, error } = await actions.updatePageView({
				id,
				shouldIncrease,
			});

			setIsLoading(false);

			if (error) {
				throw new Error("Unable to run `blogPostViews` action");
			}

			const count = data?.[0]?.count;

			if (count === undefined) {
				throw new Error("Returned data of `blogPostViews` action is unusable");
			}

			setViewCount(count);
		};

		fetchData().catch(console.error);
	});

	return isLoading || viewCount === null ? (
		<div className="inline-block h-[1lh] w-[8ch] animate-pulse rounded-lg bg-neutral-900" />
	) : (
		<p className="inline-block">{viewCount.toLocaleString()} views</p>
	);
};

// src/components/blog/ViewCounter.vue
<script setup lang="ts">
import SkeletonLoader from "@/components/common/SkeletonLoader.vue";
import { actions } from "astro:actions";
import { onMounted, ref } from "vue";

const isSSR = import.meta.env.SSR;

const { id } = defineProps<{
	id: string;
}>();

const viewCount = ref<null | number>(null);
const isLoading = ref(true);
const error = ref(null);

const fetchData = async () => {
	const { data, error } = await actions.pageViews.increase(id);

	isLoading.value = false;

	if (error) {
		throw new Error("Unable to run `pageViews.increase` action");
	}

	if (data === undefined || data[0] === undefined) {
		throw new Error(
			"Returned data of `pageViews.increase` action is unusable",
		);
	}

	viewCount.value = data[0].count;
};

onMounted(() => {
	fetchData().catch((error) => {
		error.value = error;
	});
});
</script>

<template>
	<template v-if="!error">
		<SkeletonLoader v-if="isSSR || isLoading || viewCount === null" />

		<p v-else>{{ `${viewCount.toLocaleString()} views` }}</p>
	</template>
</template>
