// src/components/experience/ExperienceFilter.tsx
import { Button } from "@/components/common/Button.tsx";
import { experienceUnimportantVisible } from "@/components/experience/experienceFilterStore.ts";
import { useStore } from "@nanostores/react";

export const ExperienceFilter = () => {
	const $unimportantItemsVisible = useStore(experienceUnimportantVisible);

	return (
		<Button
			text={$unimportantItemsVisible ? "Less please" : "Early career"}
			isActive={$unimportantItemsVisible}
			onClick={() =>
				experienceUnimportantVisible.set(!$unimportantItemsVisible)
			}
		/>
	);
};

// src/components/experience/ExperienceFilter.vue
<script setup lang="ts">
import Button from "@/components/common/Button.vue";
import { experienceFilterStore } from "@/components/experience/experienceFilterStore.ts";
</script>

<template>
	<Button
		:text="
			experienceFilterStore.experienceUnimportantVisible
				? 'Less please'
				: 'Early career'
		"
		:is-active="experienceFilterStore.experienceUnimportantVisible"
		@click="() => experienceFilterStore.toggleVisibility()" />
</template>
