// src/components/Button.tsx
import { clsx } from "clsx";
import { motion } from "motion/react";
import type { AriaAttributes, Ref, SyntheticEvent } from "react";
import { twMerge } from "tailwind-merge";
import {
	PerspectiveTextHover,
	type PerspectiveTextHoverProps,
} from "./PerspectiveTextHover";

type ButtonProps = {
	ref?: Ref<HTMLButtonElement>;
	level?: "primary" | "secondary";
	className?: string;
	onClick?: (event: SyntheticEvent<HTMLButtonElement>) => void;
} & PerspectiveTextHoverProps &
	Partial<AriaAttributes>;

export const Button = ({
	text,
	activeText,
	ref,
	level = "primary",
	isActive = false,
	className: additionalClasses,
	onClick,
	...ariaAttributes
}: ButtonProps) => {
	return (
		<motion.button
			initial="default"
			animate={isActive ? "active" : "default"}
			whileHover="hover"
			ref={ref}
			className={twMerge(
				clsx(
					"relative inline-flex items-center justify-center overflow-hidden rounded-3xl px-8 py-4 text-white",
					level === "primary" && "bg-purple",
					level === "secondary" && "bg-neutral-900",
					additionalClasses,
				),
			)}
			onClick={onClick}
			{...ariaAttributes}
		>
			<motion.div
				transition={{ duration: 0.2, ease: "easeOut" }}
				variants={{
					default: {
						translateY: "100%",
					},
					active: {
						translateY: "0",
					},
					hover: {
						translateY: "0",
					},
				}}
				className={clsx(
					"absolute h-[200%] w-[150%] rounded-[50%] bg-purple-600",
				)}
			/>
			<PerspectiveTextHover
				className="justify-center"
				text={text}
				activeText={activeText}
				isActive={isActive}
			/>
		</motion.button>
	);
};

// src/components/common/Button.vue
<script setup lang="ts">
import { computed, toRefs, useAttrs } from "vue";

const getTransitionDelayByIndex = (index: number) => `${index * 3}ms`;

defineOptions({
	inheritAttrs: false,
});

interface Props {
	text:
		| string
		| {
				default: string;
				activeText: string;
		  };
	className?: string;
	level?: "primary" | "secondary";
	size?: "small" | "medium";
	isActive?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
	level: "primary",
	size: "medium",
});

const { text, level, size, className, isActive } = toRefs(props);

const additionalProps = useAttrs();

const defaultText = computed(() =>
	typeof text.value === "string" ? text.value : text.value.default,
);

const activeText = computed(() =>
	typeof text.value === "string" ? text.value : text.value.activeText,
);

const buttonLabel = computed(() =>
	(additionalProps["aria-label"] ?? !isActive.value)
		? defaultText.value
		: activeText.value,
);

const showActiveTextOnHover =
	typeof text.value === "string" || text.value.activeText === undefined;

const styleObject = computed(() => ({
	"group relative inline-flex items-center justify-center gap-2 overflow-clip": true,
	"rounded-2xl px-6 py-3": size.value === "small",
	"rounded-3xl px-8 py-4": size.value === "medium",
	"bg-purple-500 text-white": level.value === "primary",
	"bg-neutral-100 text-black hover:text-white": level.value === "secondary",
	"active text-white": Boolean(isActive.value),
	[className.value ?? ""]: Boolean(className.value),
}));
</script>

<template>
	<button
		v-bind="additionalProps"
		type="button"
		:aria-label="buttonLabel"
		:class="styleObject">
		<div
			aria-hidden="true"
			class="absolute z-0 h-[200%] w-[150%] translate-y-full rounded-[50%] bg-purple-700 transition-transform duration-200 ease-out group-hover:translate-y-0 group-[.active]:translate-y-0" />

		<span class="z-10 flex justify-items-start whitespace-nowrap">
			<span>
				<span
					v-for="(char, index) in defaultText.split('')"
					:key="`default_text_${char}_${index}`"
					:class="{
						'transition-all duration-200 ease-out': true,
						'group-hover:-translate-y-full group-hover:opacity-0':
							showActiveTextOnHover,
						'group-[.active]:-translate-y-full group-[.active]:opacity-0':
							!showActiveTextOnHover,
						'inline-block': char !== ' ',
					}"
					:style="{
						'transition-delay': getTransitionDelayByIndex(index),
					}">
					{{ char }}
				</span>
			</span>

			<span class="absolute">
				<span
					v-for="(char, index) in activeText.split('')"
					:key="`active_text_${char}_${index}`"
					:class="{
						'translate-y-full opacity-0 transition-all duration-200 ease-out': true,
						'group-hover:translate-y-0 group-hover:opacity-100':
							showActiveTextOnHover,
						'group-[.active]:translate-y-0 group-[.active]:opacity-100':
							!showActiveTextOnHover,
						'inline-block': char !== ' ',
					}"
					:style="{
						'transition-delay': getTransitionDelayByIndex(index),
					}">
					{{ char }}
				</span>
			</span>
		</span>
	</button>
</template>
